### ISSUE TITLE
Connect dbAuth

### ISSUE THREAD

**Issue by shiningblue7** [shiningblue7/tskr#3]

**Comment by jacebenson** [comment]
Here's the docs on this.
https://redwoodjs.com/docs/authentication#setup

This should need this the following commands.

```
yarn rw setup auth dbAuth
```

Then, you'll need to let Redwood know what field you're using for your users' id and username fields In this case we're using id and email, so update those in the authFields config in /api/src/functions/auth.js (this is also the place to tell Redwood if you used a different name for the hashedPassword or salt fields):

```js
authFields: {
  id: 'id',
  username: 'email',
  hashedPassword: 'hashedPassword',
  salt: 'salt',
},
```

Then we need to add a SESSION_SECRET environment variable.
```
yarn rw g secret
```

We don't want to create login and signup pages.  This needs to be done too.

```
yarn rw g scaffold dbAuth
```
We may need to move them in the standard layout.

**Comment by jacebenson** [comment]
This is handled in #17
